server:
  port: 8080
spring:
  thymeleaf:
    cache: false #是否启用缓存，开发环境设为false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/ #模板路径
    suffix: .html # 后缀
    servlet:
      content-type: text/html; charset=utf-8
